language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: BjyR9UKod4f6drme7vJe4WD41m1Bl7zYtDtUo+g6f/VhpRE0h30FhI8ihTq36kZituBITzm8qnHZRELCFMhXh4Df3OO9r+7mCtvW0Jeu6TLbVToTY1Sxg3wszkNxqj6YbDTIsqoDh/ndUd28Gi/DHW/1dq4Fm2mdbwD2xHNZ0UpROSYNk5D8syFYY9gHIr2Sc8jICEH8gpJ5DzovvPZ85ANPTcOWwOrBg2RvbinAlHgoLGYP/+eJlwRIcA8dYYhxX0nLHn4w4YJsTBtavNB6LjrS/wQ8M89j5o1YvkfdJyfHAtbDbJzJU3GLTQn8hZy+BUw8qCf2hKRY+NZzFC1bm/hr2TN1KPqwdTtT0NSc+f2JWJEui1Q9rPyCH2LROfv+WV5Abqij/4usWVDFpeeQ9Pc9MX/epsP4uvmM40GbtedpZawgpqUaKW/Pmbfhy2yNz+aEjIRw/lrMnixyIrx3MYf0HU8lLvofsRNzDYLckgaqUwT2b0RK0/9PGy6Ihvo15i9yGrGPNu6LtlEF6ZfKUtVH4qs7D6zZ4SeFM+2YfQ8j+ZKPCSV1EQlo13OKPjRIa68pl+oi0XNbC9FEL3MH1Ai0WGD1bphyYwm+F+feTRYGTt84rDl1MGD7JkfEVqLbGlv4Css/uXJhO/zZ+SxuNpVhbg6hQgQksF1QvBDVSbg=
