language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: M3pe4Jt+GyWR0AhQh3vNs73OIdDPwRwX0VPrCaT7MdiW/t1rsB6dYeyuj7T0/BHE6PrafRefQ7vHNnw+9EyITZUKU368kribH6ZeKxDAEzFuX89Y2FN+KVZouCVwsMuBEDsXZzlM3AVZ8w93GicfvwNpz3JXy6B1jPUPGg2iSqTxr59en4D/yulnqEKJKqjTpuUBT2QPXDvs1VG8w9N6nvpwHM8o2xPk9Hgdw3Z9D49rG/stgsYZm/2nqTzCZT9nbzKK/0Bh2fBdFcc1x9okBBfVnxm1w5nSGKc1x8eiiG/qiw0594Gc71u365GLxKSmqE97X33T/jgzZPKutwfkj9R1exLBSq6l6IT1JTCumODsI5FflwjFlMjMdTz0gtZByUep3EovB9AopVgUCsxb7i+3fv2pYWAugTqmbC7WjCDVKI84579bo6C2PdCycDwrUPQqSQEwcAb+f0Qbs37bSRQANyTGEkHeLpTQSalIffuzg5ipROUXNe+MqqRiHg0s3uTnSCoGoDlBq/SszPfhr+xk9vytx/PCm0I64Z2rCyFqNCNcR/vjy2kKaJS7SxcQHvVK1QA8L7TbXYKx7m/sUPbjGjvp0d09buGMtxjsMIwASx5cFR16rCY4dNF1iVixsll2e3OKBixFMzCvTG3fVZj+zXLV3H92ZkGv4xbzrXE=
